name: ESCI203
channels:
  - conda-forge
dependencies:
  - python3
  - numpy==1.17.1
  - obspy==1.1.1
  - bokeh==2.0.1
  - jupyter==1.0.0
  - pyproj==1.9.6
  - matplotlib==3.0.3
  - ipympl==0.5.6
  - ipysheet==0.4.4
  - pip
  - pip:
    - mplstereonet==0.5